// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_MENUITEM_H
#define _UI_COMP_MENUITEM_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT menuItem
#define UI_COMP_MENUITEM_MENUITEM 0
#define UI_COMP_MENUITEM_LABEL5 1
#define UI_COMP_MENUITEM_LABEL3 2
#define UI_COMP_MENUITEM_PANEL5 3
#define UI_COMP_MENUITEM_PANEL5_IMAGE4 4
#define _UI_COMP_MENUITEM_NUM 5
lv_obj_t * ui_menuItem_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
