// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT menuItem

lv_obj_t * ui_menuItem_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_menuItem;
    cui_menuItem = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_menuItem);
    lv_obj_set_width(cui_menuItem, 240);
    lv_obj_set_height(cui_menuItem, 50);
    lv_obj_set_x(cui_menuItem, 0);
    lv_obj_set_y(cui_menuItem, 50);
    lv_obj_clear_flag(cui_menuItem, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label5;
    cui_Label5 = lv_label_create(cui_menuItem);
    lv_obj_set_width(cui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label5, 15);
    lv_obj_set_y(cui_Label5, 0);
    lv_obj_set_align(cui_Label5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Label5, "Beep");
    lv_obj_set_style_text_font(cui_Label5, &ui_font_roboto_bold_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label3;
    cui_Label3 = lv_label_create(cui_menuItem);
    lv_obj_set_width(cui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label3, -75);
    lv_obj_set_y(cui_Label3, 0);
    lv_obj_set_align(cui_Label3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(cui_Label3, "On");

    lv_obj_t * cui_Panel5;
    cui_Panel5 = lv_obj_create(cui_menuItem);
    lv_obj_set_width(cui_Panel5, 40);
    lv_obj_set_height(cui_Panel5, 40);
    lv_obj_set_x(cui_Panel5, -15);
    lv_obj_set_y(cui_Panel5, 0);
    lv_obj_set_align(cui_Panel5, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(cui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel5, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel5, lv_color_hex(0xF60F43), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image4;
    cui_Image4 = lv_img_create(cui_Panel5);
    lv_img_set_src(cui_Image4, &ui_img_img_arrow_icon_png);
    lv_obj_set_width(cui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_MENUITEM_NUM);
    children[UI_COMP_MENUITEM_MENUITEM] = cui_menuItem;
    children[UI_COMP_MENUITEM_LABEL5] = cui_Label5;
    children[UI_COMP_MENUITEM_LABEL3] = cui_Label3;
    children[UI_COMP_MENUITEM_PANEL5] = cui_Panel5;
    children[UI_COMP_MENUITEM_PANEL5_IMAGE4] = cui_Image4;
    lv_obj_add_event_cb(cui_menuItem, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_menuItem, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_menuItem_create_hook(cui_menuItem);
    return cui_menuItem;
}

