// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CHARGE_H
#define UI_CHARGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_charge
extern void ui_charge_screen_init(void);
extern void ui_charge_screen_destroy(void);
extern lv_obj_t * ui_charge;
extern lv_obj_t * ui_batt6;
extern lv_obj_t * ui_battWrng;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

