// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_charge = NULL;
lv_obj_t * ui_batt6 = NULL;
lv_obj_t * ui_battWrng = NULL;
// event funtions

// build funtions

void ui_charge_screen_init(void)
{
    ui_charge = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_charge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_charge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_charge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batt6 = lv_img_create(ui_charge);
    lv_img_set_src(ui_batt6, &ui_img_img_charge_png);
    lv_obj_set_width(ui_batt6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batt6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batt6, 0);
    lv_obj_set_y(ui_batt6, -10);
    lv_obj_set_align(ui_batt6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batt6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_batt6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_battWrng = lv_label_create(ui_charge);
    lv_obj_set_width(ui_battWrng, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battWrng, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_battWrng, 0);
    lv_obj_set_y(ui_battWrng, 25);
    lv_obj_set_align(ui_battWrng, LV_ALIGN_CENTER);
    lv_label_set_text(ui_battWrng, "Charging...");
    lv_obj_set_style_text_color(ui_battWrng, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_battWrng, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_battWrng, &ui_font_roboto_bold_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_charge_screen_destroy(void)
{
    if(ui_charge) lv_obj_del(ui_charge);

    // NULL screen variables
    ui_charge = NULL;
    ui_batt6 = NULL;
    ui_battWrng = NULL;

}
