// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_dashboard = NULL;
lv_obj_t * ui_logo = NULL;
lv_obj_t * ui_logoImg = NULL;
lv_obj_t * ui_header = NULL;
lv_obj_t * ui_measureImg = NULL;
lv_obj_t * ui_measCount = NULL;
lv_obj_t * ui_pmaNum = NULL;
lv_obj_t * ui_measure = NULL;
lv_obj_t * ui_measurement = NULL;
lv_obj_t * ui_sec = NULL;
lv_obj_t * ui_delBtn = NULL;
lv_obj_t * ui_delImg = NULL;
lv_obj_t * ui_delLbl = NULL;
lv_obj_t * ui_saveBtn = NULL;
lv_obj_t * ui_saveImg = NULL;
lv_obj_t * ui_saveLbl = NULL;
lv_obj_t * ui_overlay = NULL;
lv_obj_t * ui_alert = NULL;
lv_obj_t * ui_menu = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_bluetooth = NULL;
lv_obj_t * ui_batt = NULL;
lv_obj_t * ui_menuItem2 = NULL;
lv_obj_t * ui_beepLbl = NULL;
lv_obj_t * ui_beepValue = NULL;
lv_obj_t * ui_changeVal = NULL;
lv_obj_t * ui_arr = NULL;
lv_obj_t * ui_menuItem3 = NULL;
lv_obj_t * ui_LanguageLbl = NULL;
lv_obj_t * ui_LanguegValue = NULL;
lv_obj_t * ui_changeVal2 = NULL;
lv_obj_t * ui_arr2 = NULL;
lv_obj_t * ui_batt2 = NULL;
lv_obj_t * ui_batt3 = NULL;
lv_obj_t * ui_batt4 = NULL;
lv_obj_t * ui_batt5 = NULL;
// event funtions
void ui_event_dashboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        scrollMenu_Animation(ui_menu, 0);
        _ui_flag_modify(ui_overlay, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_flag_modify(ui_overlay, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        hideMenu_Animation(ui_menu, 0);
    }
}

void ui_event_delBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        measure_delete_event(e);
    }
}

void ui_event_saveBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        measure_save_event(e);
    }
}

void ui_event_changeVal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        changeBeep(e);
    }
}

void ui_event_changeVal2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        changeLang(e);
    }
}

// build funtions

void ui_dashboard_screen_init(void)
{
    ui_dashboard = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_dashboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dashboard, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dashboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo = lv_obj_create(ui_dashboard);
    lv_obj_set_width(ui_logo, 240);
    lv_obj_set_height(ui_logo, 50);
    lv_obj_set_align(ui_logo, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_logo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_logo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_logo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_logo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logoImg = lv_img_create(ui_logo);
    lv_img_set_src(ui_logoImg, &ui_img_img_hello_logo_png);
    lv_obj_set_width(ui_logoImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logoImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_logoImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logoImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logoImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_header = lv_obj_create(ui_dashboard);
    lv_obj_set_width(ui_header, 240);
    lv_obj_set_height(ui_header, 50);
    lv_obj_set_x(ui_header, 0);
    lv_obj_set_y(ui_header, 50);
    lv_obj_clear_flag(ui_header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_measureImg = lv_img_create(ui_header);
    lv_img_set_src(ui_measureImg, &ui_img_img_timer_red_png);
    lv_obj_set_width(ui_measureImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_measureImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_measureImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_measureImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_measCount = lv_label_create(ui_header);
    lv_obj_set_width(ui_measCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_measCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_measCount, 37);
    lv_obj_set_y(ui_measCount, 2);
    lv_label_set_text(ui_measCount, "| 1");
    lv_obj_set_style_text_font(ui_measCount, &ui_font_reboto_bold_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pmaNum = lv_label_create(ui_header);
    lv_obj_set_width(ui_pmaNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pmaNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pmaNum, 0);
    lv_obj_set_y(ui_pmaNum, 2);
    lv_obj_set_align(ui_pmaNum, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_pmaNum, "0.0 L");
    lv_obj_set_style_text_font(ui_pmaNum, &ui_font_roboto_bold_17, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_measure = lv_obj_create(ui_dashboard);
    lv_obj_set_width(ui_measure, 240);
    lv_obj_set_height(ui_measure, 50);
    lv_obj_set_x(ui_measure, 0);
    lv_obj_set_y(ui_measure, 120);
    lv_obj_clear_flag(ui_measure, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_measure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_measure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_measure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_measure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_measurement = lv_label_create(ui_measure);
    lv_obj_set_width(ui_measurement, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_measurement, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_measurement, -35);
    lv_obj_set_y(ui_measurement, 5);
    lv_obj_set_align(ui_measurement, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_measurement, "0.0");
    lv_obj_set_style_text_color(ui_measurement, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_measurement, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_measurement, &ui_font_reboto_reguar_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sec = lv_label_create(ui_measure);
    lv_obj_set_width(ui_sec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sec, 5);
    lv_obj_set_y(ui_sec, 13);
    lv_obj_set_align(ui_sec, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_sec, "sec");
    lv_obj_set_style_text_color(ui_sec, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sec, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sec, &ui_font_reboto_bold_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_delBtn = lv_btn_create(ui_dashboard);
    lv_obj_set_width(ui_delBtn, 105);
    lv_obj_set_height(ui_delBtn, 50);
    lv_obj_set_x(ui_delBtn, -60);
    lv_obj_set_y(ui_delBtn, 90);
    lv_obj_set_align(ui_delBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_delBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_delBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_delBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_delBtn, lv_color_hex(0xF60F43), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_delBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_delBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_delImg = lv_img_create(ui_delBtn);
    lv_img_set_src(ui_delImg, &ui_img_img_trash_icon_png);
    lv_obj_set_width(ui_delImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_delImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_delImg, -1);
    lv_obj_set_y(ui_delImg, 0);
    lv_obj_set_align(ui_delImg, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_delImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_delImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_delLbl = lv_label_create(ui_delBtn);
    lv_obj_set_width(ui_delLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_delLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_delLbl, 10);
    lv_obj_set_y(ui_delLbl, 0);
    lv_obj_set_align(ui_delLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_delLbl, "Delete");
    lv_obj_set_style_text_color(ui_delLbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_delLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_delLbl, &ui_font_roboto_bold_17, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_saveBtn = lv_btn_create(ui_dashboard);
    lv_obj_set_width(ui_saveBtn, 105);
    lv_obj_set_height(ui_saveBtn, 50);
    lv_obj_set_x(ui_saveBtn, 60);
    lv_obj_set_y(ui_saveBtn, 90);
    lv_obj_set_align(ui_saveBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_saveBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_saveBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_saveBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_saveBtn, lv_color_hex(0x28B891), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_saveBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_saveImg = lv_img_create(ui_saveBtn);
    lv_img_set_src(ui_saveImg, &ui_img_img_save_icon_png);
    lv_obj_set_width(ui_saveImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_saveImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_saveImg, -1);
    lv_obj_set_y(ui_saveImg, 0);
    lv_obj_set_align(ui_saveImg, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_saveImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_saveImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_saveLbl = lv_label_create(ui_saveBtn);
    lv_obj_set_width(ui_saveLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_saveLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_saveLbl, 13);
    lv_obj_set_y(ui_saveLbl, 0);
    lv_obj_set_align(ui_saveLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_saveLbl, "Save");
    lv_obj_set_style_text_color(ui_saveLbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_saveLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_saveLbl, &ui_font_roboto_bold_17, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_overlay = lv_obj_create(ui_dashboard);
    lv_obj_set_width(ui_overlay, 240);
    lv_obj_set_height(ui_overlay, 280);
    lv_obj_set_align(ui_overlay, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_overlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_overlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_overlay, lv_color_hex(0x3F3F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_overlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_overlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alert = lv_label_create(ui_dashboard);
    lv_obj_set_width(ui_alert, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alert, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_alert, 0);
    lv_obj_set_y(ui_alert, 47);
    lv_obj_set_align(ui_alert, LV_ALIGN_CENTER);
    lv_label_set_text(ui_alert, "");
    lv_obj_set_style_text_font(ui_alert, &ui_font_roboto_bold_17, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menu = lv_obj_create(ui_dashboard);
    lv_obj_set_width(ui_menu, 240);
    lv_obj_set_height(ui_menu, 280);
    lv_obj_set_x(ui_menu, 0);
    lv_obj_set_y(ui_menu, 255);
    lv_obj_set_align(ui_menu, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_menu);
    lv_img_set_src(ui_Image10, &ui_img_332468020);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image10, 0);
    lv_obj_set_y(ui_Image10, -25);
    lv_obj_set_align(ui_Image10, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bluetooth = lv_img_create(ui_menu);
    lv_img_set_src(ui_bluetooth, &ui_img_img_smartphone_png);
    lv_obj_set_width(ui_bluetooth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bluetooth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bluetooth, -70);
    lv_obj_set_y(ui_bluetooth, 27);
    lv_obj_set_align(ui_bluetooth, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_bluetooth, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bluetooth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batt = lv_img_create(ui_menu);
    lv_img_set_src(ui_batt, &ui_img_img_battery_full_png);
    lv_obj_set_width(ui_batt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batt, -25);
    lv_obj_set_y(ui_batt, 25);
    lv_obj_set_align(ui_batt, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_batt, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_batt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menuItem2 = lv_obj_create(ui_menu);
    lv_obj_remove_style_all(ui_menuItem2);
    lv_obj_set_width(ui_menuItem2, 240);
    lv_obj_set_height(ui_menuItem2, 50);
    lv_obj_set_x(ui_menuItem2, 0);
    lv_obj_set_y(ui_menuItem2, 70);
    lv_obj_clear_flag(ui_menuItem2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_beepLbl = lv_label_create(ui_menuItem2);
    lv_obj_set_width(ui_beepLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_beepLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_beepLbl, 15);
    lv_obj_set_y(ui_beepLbl, 0);
    lv_obj_set_align(ui_beepLbl, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_beepLbl, "Beep");
    lv_obj_set_style_text_font(ui_beepLbl, &ui_font_roboto_bold_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_beepValue = lv_label_create(ui_menuItem2);
    lv_obj_set_width(ui_beepValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_beepValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_beepValue, -75);
    lv_obj_set_y(ui_beepValue, 0);
    lv_obj_set_align(ui_beepValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_beepValue, "On");

    ui_changeVal = lv_obj_create(ui_menuItem2);
    lv_obj_set_width(ui_changeVal, 45);
    lv_obj_set_height(ui_changeVal, 45);
    lv_obj_set_x(ui_changeVal, -15);
    lv_obj_set_y(ui_changeVal, 0);
    lv_obj_set_align(ui_changeVal, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_changeVal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_changeVal, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_changeVal, lv_color_hex(0xF60F43), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changeVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_changeVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arr = lv_img_create(ui_changeVal);
    lv_img_set_src(ui_arr, &ui_img_img_arrow_icon_png);
    lv_obj_set_width(ui_arr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_arr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_arr, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_arr, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_arr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menuItem3 = lv_obj_create(ui_menu);
    lv_obj_remove_style_all(ui_menuItem3);
    lv_obj_set_width(ui_menuItem3, 240);
    lv_obj_set_height(ui_menuItem3, 50);
    lv_obj_set_x(ui_menuItem3, 0);
    lv_obj_set_y(ui_menuItem3, 150);
    lv_obj_clear_flag(ui_menuItem3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LanguageLbl = lv_label_create(ui_menuItem3);
    lv_obj_set_width(ui_LanguageLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LanguageLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LanguageLbl, 15);
    lv_obj_set_y(ui_LanguageLbl, 0);
    lv_obj_set_align(ui_LanguageLbl, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LanguageLbl, "Language");
    lv_obj_set_style_text_font(ui_LanguageLbl, &ui_font_roboto_bold_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LanguegValue = lv_label_create(ui_menuItem3);
    lv_obj_set_width(ui_LanguegValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LanguegValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LanguegValue, -75);
    lv_obj_set_y(ui_LanguegValue, 0);
    lv_obj_set_align(ui_LanguegValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LanguegValue, "EN");

    ui_changeVal2 = lv_obj_create(ui_menuItem3);
    lv_obj_set_width(ui_changeVal2, 45);
    lv_obj_set_height(ui_changeVal2, 45);
    lv_obj_set_x(ui_changeVal2, -15);
    lv_obj_set_y(ui_changeVal2, 0);
    lv_obj_set_align(ui_changeVal2, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_changeVal2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_changeVal2, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_changeVal2, lv_color_hex(0xF60F43), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changeVal2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_changeVal2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arr2 = lv_img_create(ui_changeVal2);
    lv_img_set_src(ui_arr2, &ui_img_img_arrow_icon_png);
    lv_obj_set_width(ui_arr2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_arr2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_arr2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_arr2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_arr2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batt2 = lv_img_create(ui_menu);
    lv_img_set_src(ui_batt2, &ui_img_img_battery_75_png);
    lv_obj_set_width(ui_batt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batt2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_batt2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batt2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_batt2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batt3 = lv_img_create(ui_menu);
    lv_img_set_src(ui_batt3, &ui_img_img_battery_50_png);
    lv_obj_set_width(ui_batt3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batt3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_batt3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batt3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_batt3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batt4 = lv_img_create(ui_menu);
    lv_img_set_src(ui_batt4, &ui_img_img_battery_empty_png);
    lv_obj_set_width(ui_batt4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batt4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_batt4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batt4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_batt4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batt5 = lv_img_create(ui_menu);
    lv_img_set_src(ui_batt5, &ui_img_img_charge_png);
    lv_obj_set_width(ui_batt5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batt5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_batt5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batt5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_batt5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_delBtn, ui_event_delBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_saveBtn, ui_event_saveBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_changeVal, ui_event_changeVal, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_changeVal2, ui_event_changeVal2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dashboard, ui_event_dashboard, LV_EVENT_ALL, NULL);

}

void ui_dashboard_screen_destroy(void)
{
    if(ui_dashboard) lv_obj_del(ui_dashboard);

    // NULL screen variables
    ui_dashboard = NULL;
    ui_logo = NULL;
    ui_logoImg = NULL;
    ui_header = NULL;
    ui_measureImg = NULL;
    ui_measCount = NULL;
    ui_pmaNum = NULL;
    ui_measure = NULL;
    ui_measurement = NULL;
    ui_sec = NULL;
    ui_delBtn = NULL;
    ui_delImg = NULL;
    ui_delLbl = NULL;
    ui_saveBtn = NULL;
    ui_saveImg = NULL;
    ui_saveLbl = NULL;
    ui_overlay = NULL;
    ui_alert = NULL;
    ui_menu = NULL;
    ui_Image10 = NULL;
    ui_bluetooth = NULL;
    ui_batt = NULL;
    ui_menuItem2 = NULL;
    ui_beepLbl = NULL;
    ui_beepValue = NULL;
    ui_changeVal = NULL;
    ui_arr = NULL;
    ui_menuItem3 = NULL;
    ui_LanguageLbl = NULL;
    ui_LanguegValue = NULL;
    ui_changeVal2 = NULL;
    ui_arr2 = NULL;
    ui_batt2 = NULL;
    ui_batt3 = NULL;
    ui_batt4 = NULL;
    ui_batt5 = NULL;

}
