// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_DASHBOARD_H
#define UI_DASHBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_dashboard
extern void ui_dashboard_screen_init(void);
extern void ui_dashboard_screen_destroy(void);
extern void ui_event_dashboard(lv_event_t * e);
extern lv_obj_t * ui_dashboard;
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_logoImg;
extern lv_obj_t * ui_header;
extern lv_obj_t * ui_measureImg;
extern lv_obj_t * ui_measCount;
extern lv_obj_t * ui_pmaNum;
extern lv_obj_t * ui_measure;
extern lv_obj_t * ui_measurement;
extern lv_obj_t * ui_sec;
extern void ui_event_delBtn(lv_event_t * e);
extern lv_obj_t * ui_delBtn;
extern lv_obj_t * ui_delImg;
extern lv_obj_t * ui_delLbl;
extern void ui_event_saveBtn(lv_event_t * e);
extern lv_obj_t * ui_saveBtn;
extern lv_obj_t * ui_saveImg;
extern lv_obj_t * ui_saveLbl;
extern lv_obj_t * ui_overlay;
extern lv_obj_t * ui_alert;
extern lv_obj_t * ui_menu;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_bluetooth;
extern lv_obj_t * ui_batt;
extern lv_obj_t * ui_menuItem2;
extern lv_obj_t * ui_beepLbl;
extern lv_obj_t * ui_beepValue;
extern void ui_event_changeVal(lv_event_t * e);
extern lv_obj_t * ui_changeVal;
extern lv_obj_t * ui_arr;
extern lv_obj_t * ui_menuItem3;
extern lv_obj_t * ui_LanguageLbl;
extern lv_obj_t * ui_LanguegValue;
extern void ui_event_changeVal2(lv_event_t * e);
extern lv_obj_t * ui_changeVal2;
extern lv_obj_t * ui_arr2;
extern lv_obj_t * ui_batt2;
extern lv_obj_t * ui_batt3;
extern lv_obj_t * ui_batt4;
extern lv_obj_t * ui_batt5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

