// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LOAD_H
#define UI_LOAD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_load
extern void ui_load_screen_init(void);
extern void ui_load_screen_destroy(void);
extern lv_obj_t * ui_load;
extern lv_obj_t * ui_logoImg2;
extern lv_obj_t * ui_bye;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

