// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_load = NULL;
lv_obj_t * ui_logoImg2 = NULL;
lv_obj_t * ui_bye = NULL;
// event funtions

// build funtions

void ui_load_screen_init(void)
{
    ui_load = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_load, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_load, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_load, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logoImg2 = lv_img_create(ui_load);
    lv_img_set_src(ui_logoImg2, &ui_img_img_hello_logo_png);
    lv_obj_set_width(ui_logoImg2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logoImg2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_logoImg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logoImg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logoImg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bye = lv_label_create(ui_load);
    lv_obj_set_width(ui_bye, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bye, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bye, 0);
    lv_obj_set_y(ui_bye, 60);
    lv_obj_set_align(ui_bye, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bye, "Bye");
    lv_obj_add_flag(ui_bye, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_bye, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bye, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bye, &ui_font_reboto_bold_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_load_screen_destroy(void)
{
    if(ui_load) lv_obj_del(ui_load);

    // NULL screen variables
    ui_load = NULL;
    ui_logoImg2 = NULL;
    ui_bye = NULL;

}
