// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_load.h"
#include "screens/ui_dashboard.h"
#include "screens/ui_charge.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * scrollMenu_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * hideMenu_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_img_hello_logo_png);    // assets/img/hello_logo.png
LV_IMG_DECLARE(ui_img_img_timer_red_png);    // assets/img/timer_red.png
LV_IMG_DECLARE(ui_img_img_trash_icon_png);    // assets/img/trash_icon.png
LV_IMG_DECLARE(ui_img_img_save_icon_png);    // assets/img/save_icon.png
LV_IMG_DECLARE(ui_img_332468020);    // assets/img/icons8-horizontal-line-75.png
LV_IMG_DECLARE(ui_img_img_smartphone_png);    // assets/img/smartphone.png
LV_IMG_DECLARE(ui_img_img_battery_full_png);    // assets/img/battery_full.png
LV_IMG_DECLARE(ui_img_img_arrow_icon_png);    // assets/img/arrow_icon.png
LV_IMG_DECLARE(ui_img_img_battery_75_png);    // assets/img/battery_75.png
LV_IMG_DECLARE(ui_img_img_battery_50_png);    // assets/img/battery_50.png
LV_IMG_DECLARE(ui_img_img_battery_empty_png);    // assets/img/battery_empty.png
LV_IMG_DECLARE(ui_img_img_charge_png);    // assets/img/charge.png

// FONTS
LV_FONT_DECLARE(ui_font_reboto_bold_24);
LV_FONT_DECLARE(ui_font_reboto_reguar_60);
LV_FONT_DECLARE(ui_font_roboto_bold_17);
LV_FONT_DECLARE(ui_font_roboto_bold_20);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
