// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void measure_delete_event(lv_event_t * e);
void measure_save_event(lv_event_t * e);
void changeBeep(lv_event_t * e);
void changeLang(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
